language: cpp
compiler:
 - gcc
before_install:
 - wget --output-document arduino-ide.tgz http://arduino.cc/download.php?f=/arduino-1.5.8-linux64.tgz
 - sudo apt-get install aptitude
 - sudo aptitude update
install:
 - tar -xf arduino-ide.tgz
 - sudo mv arduino-1.5.8/ /usr/local/share/arduino
 - sudo aptitude -y install ia32-libs
 - git clone -b ide1.5x https://github.com/justonia/ino.git
 - cd ino && sudo make install && cd ../
 - sudo pip install jinja2
 - sudo pip install pyserial

script:
 - pwd
 - ino --help
 - ino init -t test
 - ls test
 - ino build -m ${MODEL}
 
env:
 - MODEL=mega2560
# - FOLDER=examples/FormattingSerialDebug
# - FOLDER=examples/SerialDebug
# - FOLDER=examples/LedDebug

global:
 - ARDUINO_IDE_VERSION='1.5.8'

#notifications:
#  email:
#  - rlogiacco@gmail.com
