language: c
before_install:
 - sudo apt-get update -qq
install:
 - sudo apt-get install -qq gcc-avr binutils-avr avr-libc
script: 
 - make MCU=atmega32 TARGET=LedDebug
 - make MCU=atmega32 TARGET=SerialDebug
 - make MCU=atmega32 TARGET=FormattingSerialDebug

#notifications:
#  email:
#  - rlogiacco@gmail.com
