language: python
install: 
 - gem install fpm
 - curl -s http://arduino.cc/download.php?f=/arduino-${ARDUINO_IDE_VERSION}-linux64.tgz | sudo tar xz -C /opt
 - git clone -q https://github.com/BrianAdams/hwci-scripts ../hwci-scripts && ../hwci-scripts/bin/setup.sh
 - sudo apt-get install cppcheck

script:
 - "   env USER_LIB_PATH=$PWD/../ ARDUINO_DIR=/opt/arduino-${ARDUINO_IDE_VERSION} ../hwci-scripts/bin/arduino_make.sh -C SerialDebug && echo pass:$e >> results || echo fail:$e >> results "
 - cat results
 - 'cut -d: -f1 results | sort | uniq -c'
 - test `grep -c fail results` -eq 0
env:
 global:
  - ARDUINO_IDE_VERSION='1.5.8'
  - MAIN_CLASS=SerialDebug
