language: python
install: 
 - gem install fpm
 - wget --output-document arduino-ide.tgz http://arduino.cc/download.php?f=/arduino-1.5.8-linux64.tgz
 - sudo tar xzf arduino-ide.tgz -C /opt
 - git clone -q https://github.com/BrianAdams/hwci-scripts ../hwci-scripts && ../hwci-scripts/bin/setup.sh
 - sudo apt-get install cppcheck

script:
 - "   env USER_LIB_PATH=$PWD/../ ARDUINO_DIR=/opt/arduino-${ARDUINO_IDE_VERSION} ../hwci-scripts/bin/arduino_make.sh -C ${MAIN_CLASS} && echo pass:$e >> results || echo fail:$e >> results "
 - cat results
 - 'cut -d: -f1 results | sort | uniq -c'
 - test `grep -c fail results` -eq 0
env:
 - MAIN_CLASS=SerialDebug.cpp
 - MAIN_CLASS=FormattingSerialDebug.cpp
 - MAIN_CLASS=LedDebug.cpp

global:
 - ARDUINO_IDE_VERSION='1.5.8'
